name: Run main.py script for list of store number range - 22-26

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiofiles asyncio aiohttp requests logging

    - name: Run the main.py script
      run: |
        python main.py 22 23 24 25 26

    - name: Wait for lock to be released
      run: |
        while [ -f .gitlock ]; do
          echo "Waiting for lock to be released..."
          sleep 60  # Wait for 1 minute before checking again
        done

    - name: Acquire lock
      run: |
        echo "Acquiring lock..."
        echo "Locked by $GITHUB_RUN_ID" > .gitlock
        git add .gitlock
        git commit -m "Acquiring lock by run $GITHUB_RUN_ID"
        git push origin main

    - name: Commit and push changes
      if: success()  # Only run this step if the previous steps were successful
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Updated store menu as of $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        git push origin main

    - name: Release lock
      run: |
        echo "Releasing lock..."
        git rm .gitlock
        git commit -m "Releasing lock by run $GITHUB_RUN_ID"
        git push origin main
