name: Run main.py script for list of store number range - 2-6

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Adjust this to the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiofiles asyncio aiohttp requests logging

    - name: Run the main.py script
      run: |
        python main.py 2 3 4 5 6

    - name: Commit and push changes
      if: success()  # Only run this step if the previous steps were successful
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated store menu as of $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push origin main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
