name: Run main.py script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Adjust this to the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiofiles aiohttp asyncio requests logging

    - name: Run the main.py script
      run: |
        python main.py
